### ISSUE TITLE
Can't install underthesea v1.1.6rc2

### ISSUE THREAD

**Issue by dthphuong** [magizbox/underthesea#174]
I install UnderTheSea library with the pip command below:
`pip install underthesea==1.1.6rc2`
But I receive an error in the image below:
![](https://scontent.fsgn5-4.fna.fbcdn.net/v/t34.0-12/26803872_949858295183207_632784373_n.png?oh=81283e477f76ba962d05e595ebfb1d28&oe=5A58C611)

Best regards,

**Comment by rain1024** [comment]
It seem has an error when you try to install `xgboost` in your system

Please try install xgboost separately

```
pip install xgboost
``` 

After xgboost is installed successfully, you can install `underthesea`

```
pip install underthesea==1.1.6rc2
```

**Comment by dthphuong** [comment]
@rain1024: I have the same issue when try install `xgboost` separately

**Comment by rain1024** [comment]
@dthphuong Can you give your error log image?

**Comment by dthphuong** [comment]
@rain1024 
 ![](https://scontent.fsgn5-4.fna.fbcdn.net/v/t34.0-0/p280x280/26754341_949880228514347_257651476_n.png?oh=eb4db53dc9163fc040b7ccd13e1a60da&oe=5A59F43A)

**Comment by rain1024** [comment]
You can install xgboost in windows by following this link https://stackoverflow.com/questions/33749735/how-to-install-xgboost-package-in-python-windows-platform

By the way, `windows`, `mac os` is not officially supported in `underthesea`. You can use `underthesea` a lot easier in ubuntu or other linux operating system

**Comment by dthphuong** [comment]
@rain1024  Thanks for your supporting 👍

**Comment by YannDubs** [comment]
@rain1024 I think this issue should be reopened. The problem here is that `underthesea` requires `languageflow` which requires `xgboost` which requires a `gcc compiler` (regardless of OS). So by doing this you force your users to have a gcc compiler for something they will not even use - I don't see xgboost used anywhere in underthesea. I think this is actually a big issue and a barrier of entry for new joiners (mac OS need : `brew install gcc@5`, ubuntu needs `apt-get install build-essential ` and centos needs `yum groupinstall 'Development Tools'`).

I would strongly suggest to either make a conditional import of `languageflow` in `underthesea` or a conditional import of `xgboost` in `languageflow`.

Example in languageflow/languageflow/model/xgboost.py:
"""python
... 

try:
    import xgboost as xgb
except ImportError:
    pass

...

class XGBoostClassifier(BaseEstimator, ClassifierMixin):
    def __init__(...):
        check_import('xgboost', to_use='XGBoostClassifier')
        
"""

with:

"""python
def check_import(module, to_use=None):
    """Check whether the given module is imported."""
    if module not in sys.modules:
        if to_use is None:
            error = '{} module not imported. Try "pip install {}".'.format(module, module)
            raise ImportError(error)
        else:
            error = 'You need {} to use {}. Try "pip install {}".'.format(module, to_use, module)
            raise ImportError(error)
"""

Or use the same function and conditional import in `underthesea` (i didn't found where it uses languageflow though).

In general this is good practice when you have to import very large/unstable/hard to install libraries only for a small task. So that people that do not use `underthesea` for classification do not need to figure out how to install components that they will not use.

**Comment by rain1024** [comment]
@YannDubs Yes. You're right. It's my mistake to require xgboost in languageflow. It will be fixed soon.

**Comment by YannDubs** [comment]
Hey @rain1024 I was wondering whether there were any updates on this ? :)

**Comment by rain1024** [comment]
@YannDubs 

The straight forward strategy in this issue is remove xgboost in setup.py file in languageflow module.

However I am preparing for a natural language processing conference in Vietnam. So I think it will be fixed next 2 weeks.

Can you give any help in this situation? Pull requests are always welcome.

**Comment by rain1024** [comment]
@YannDubs I'm fixing this issue in pull request #179 

Version 1.1.7 is going to be released in next few days

**Comment by YannDubs** [comment]
Thank you :) sorry but I really didn't have time to have a look at that before !

**Comment by huylc12343** [comment]
help me about this error pleas 
Collecting underthesea
  Using cached underthesea-6.8.0-py3-none-any.whl.metadata (14 kB)
Collecting Click>=6.0 (from underthesea)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: python-crfsuite>=0.9.6 in d:\nlp\myenv\lib\site-packages (from underthesea) (0.9.10)
Collecting nltk (from underthesea)
  Using cached nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: tqdm in d:\nlp\myenv\lib\site-packages (from underthesea) (4.66.4)
Requirement already satisfied: requests in d:\nlp\myenv\lib\site-packages (from underthesea) (2.31.0)
Requirement already satisfied: joblib in d:\nlp\myenv\lib\site-packages (from underthesea) (1.4.2)
Requirement already satisfied: scikit-learn in d:\nlp\myenv\lib\site-packages (from underthesea) (1.4.2)
Requirement already satisfied: PyYAML in d:\nlp\myenv\lib\site-packages (from underthesea) (6.0.1)
Collecting underthesea-core==1.0.4 (from underthesea)
  Using cached underthesea_core-1.0.4.tar.gz (560 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 290, in __init__
    super().__init__(
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_internal\utils\misc.py", line 745, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "D:\NLP\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huylc\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'maturin'
